# This is a cronjob for PR reminders
name: Daily PR Reminder

on:
  workflow_dispatch:
  schedule:
    - cron: '0 11 * * 1-5'

env:
  DEVOPS_DIR: devops

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: List Pull Requests
      uses: buildsville/list-pull-requests@v1
      id: list
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        labels: '[]'
        skip_hour: '0'
    - name: Check-out repository
      uses: actions/checkout@v2
      with:
        repository: Mawdac/github-actions-sandbox
        token: ${{ secrets.GITHUB_TOKEN }}
        path: ${{ env.DEVOPS_DIR }}
    - name: Parse output
      run: |
        output=$(python ${{ env.DEVOPS_DIR }}/.github/parse-pr.py '${{ steps.list.outputs.pulls }})
        output="${output//'%'/'%25'}"
        output="${output//$'\n'/'%0A'}"
        output="${output//$'\r'/'%0D'}" 
        echo "::set-output name=pull-reqs::$output"
      id: parse
    - name: Print PRs
      run: echo "${{ steps.parse.outputs.pull-reqs }}"
      shell: sh