# This is a cronjob for PR reminders
name: Daily PR Reminder

on:
  workflow_dispatch:
  schedule:
    - cron: '0 11 * * 1-5'

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: List Pull Requests
        uses: buildsville/list-pull-requests@v1
        id: list
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          labels: '[]'
          skip_hour: '0'  
      - name: Print Output
        run: echo '${{ steps.list.outputs.pulls }}'
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Parse PRs
        run: python ${{ github.action_path }}/parse-pr.py '${{ steps.list.outputs.pulls }}'