# This is a cronjob for PR reminders
#
# I created this before I knew it was already a feature
name: Daily PR Reminder

on:
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: List Pull Requests
      uses: buildsville/list-pull-requests@v1
      id: list
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        labels: '[]'
        skip_hour: '0'
    - name: Check-out repository # defaults to the current
      uses: actions/checkout@v2
    - name: Parse output
      run: |
        output=$(python .github/parse-pr.py '${{ steps.list.outputs.pulls }}')
        echo "::set-output name=markdown::$output"
      id: parse
    - name: Print PRs
      run: echo '${{ steps.parse.outputs.markdown }}'
      shell: sh
