# This is a cronjob for PR reminders
name: Daily PR Reminder

on:
  workflow_dispatch:
  schedule:
    - cron: '0 11 * * 1-5'

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: List Pull Requests
        uses: buildsville/list-pull-requests@v1
        id: list
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          labels: '[]'
          skip_hour: '0'  
      - name: output
        run: echo '${{ steps.list.outputs.pulls }}'
          
