---
name: Tag Cleanup

on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'feature')
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo The PR was merged
