name: PR Label Check

on:
  pull_request:
    types: [opened, reopened, labeled, unlabeled]

jobs:
  check-labels:
    runs-on: ubuntu-latest

    steps:
    - uses: jesusvasquez333/verify-pr-label-action@v1.4.0
      name: validate labels
      with:
        github-token: '${{ secrets.GITHUB_TOKEN }}'
        valid-labels: 'patch, minor, major'
        invalid-labels: 'do not merge, wip'
        disable-reviews: true
