name: Pull Request Check

on:
  pull_request:
    types: [opened, reopened, labeled, unlabeled, synchronize]

jobs:
  check:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
    - uses: actions/labeler@v4
      if: |
        ${{!contains(github.event.pull_request.labels.*.name, 'wip')
        !contains(github.event.pull_request.labels.*.name, 'do not merge') ||
        !contains(github.event.pull_request.labels.*.name, 'patch') ||
        !contains(github.event.pull_request.labels.*.name, 'minor') ||
        !contains(github.event.pull_request.labels.*.name, 'major')}}
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"

    - uses: jesusvasquez333/verify-pr-label-action@v1.4.0
      with:
        github-token: '${{ secrets.GITHUB_TOKEN }}'
        valid-labels: 'patch, minor, major'
        invalid-labels: 'do not merge, wip'
        # disable-reviews: true
