name: Bump release version

on:
  pull_request:
    branches:
      - "main"
    types: [closed]

jobs:
  bump:
    runs-on: ubuntu-latest

    if: github.event.pull_request.merged == true
    steps:

    - name: Get PR labels
      id: pr-labels
      uses: joerick/pr-labels-action@v1.0.6

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: bump version
      run: |
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
        git reset --soft HEAD~1
        git add .
        COMMIT_MESSAGE=$(git log --format=%B --reverse HEAD..HEAD@{1})
        echo $COMMIT_MESSAGE
        if [ -n "$GITHUB_PR_LABEL_MAJOR" ]; then
          npm version major -m "$COMMIT_MESSAGE Bump major version [github ci]"
        elif [ -n "$GITHUB_PR_LABEL_MINOR" ]; then
          npm version minor -m "$COMMIT_MESSAGE Bump minor version [github ci]"
        elif [ -n "$GITHUB_PR_LABEL_PATCH" ]; then
          npm version patch -m "$COMMIT_MESSAGE Bump patch version [github ci]"
        else
          echo "Invalid label, must be patch, minor or major."
          exit 1
        fi
        git push --follow-tags -f
  release:
    needs: bump
    uses: ./.github/workflows/release.yml

  preview:
    needs: bump
    uses: ./.github/workflows/release-preview.yml

  notify:
    needs: bump
    uses: ./.github/workflows/release-notify.yml
