name: Bump release version

# on:
#   push:
#     branches:
#       - "main"
on:
  pull_request:
    branches:
      - "main"
    types: [closed]

jobs:
  bump:
    runs-on: ubuntu-latest

    if: github.event.pull_request.merged == true
    steps:

    - name: Get PR labels
      id: pr-labels
      uses: joerick/pr-labels-action@v1.0.6

    - uses: actions/checkout@v2 
    - name: bump version
      run: |
        if [ -n "$GITHUB_PR_LABEL_MAJOR" ]; then
          npm version major -m "Bump major version"
          echo "It's a major!"
        elif [ -n "$GITHUB_PR_LABEL_MINOR" ]; then
          npm version minor -m "Bump minor version"
          echo "It's a minor!"
        elif [ -n "$GITHUB_PR_LABEL_PATCH" ]; then
          npm version patch -m "Bump patch version"
          echo "It's a patch!"
        else
          echo "Invalid label, must be patch, minor or major."
          exit 1
        fi
        git push
