name: Build and release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  changelog:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check output
        run: echo ${{steps.github_release.outputs.changelog}}

      - name: Create Release
        uses: softprops/action-gh-release@v0.1.14
        with:
          body: ${{steps.github_release.outputs.changelog}}
