name: Bump release version

on:
  pull_request:
    branches:
      - "main"
    types: [closed]

jobs:
  bump:
    runs-on: ubuntu-latest

    if: github.event.pull_request.merged == true
    steps:

    - name: Get PR labels
      id: pr-labels
      uses: joerick/pr-labels-action@v1.0.6

    - uses: actions/checkout@v2
    - name: bump version
      run: |
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
        MESSAGE=$(git log --format=%B --reverse HEAD~..HEAD)
        if [ -n "$GITHUB_PR_LABEL_MAJOR" ]; then
          npm version major -m "$MESSAGE Major bump to %s [skip ci]"
        elif [ -n "$GITHUB_PR_LABEL_MINOR" ]; then
          npm version minor -m "$MESSAGE Minor bump to %s [skip ci]"
        elif [ -n "$GITHUB_PR_LABEL_PATCH" ]; then
          npm version patch -m "$MESSAGE Patch bump to %s [skip ci]"
        else
          echo "Invalid label, must be patch, minor or major."
          exit 1
        fi
  release:
    needs: bump
    uses: ./.github/workflows/release.yml

  preview:
    needs: bump
    uses: ./.github/workflows/release-preview.yml

  notify:
    needs: bump
    uses: ./.github/workflows/release-notify.yml
