name: Build and release

on:
  workflow_call:

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check output
        run: echo ${{ steps.github_release.outputs.changelog }}
