name: Reusable

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string

jobs:
  echo:
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: ${{ inputs.branch }}

    steps:
    - name: Echo branch name
      run: |
        if [[ $BRANCH_NAME == 'refs/heads/reusable-workflows' ]]; then
          echo $BRANCH_NAME
        else
          echo nope
        fi