name: Test recursive workflows

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  recursive:
    runs-on: ubuntu-latest

    steps:
    - name: notify
      run: echo "another workflow probably triggered this"
